
def liste_joueurss():

    liste_joueurs_baseball_colombie={"Pitchers":['Ángel Vílchez','Carlos Mario Díaz','Dewin Pérez','Ezequiel Zabaleta','Hernán Guzmán','Hernando Chiquillo','Jaider Rocha','José Calero','Luis Yendis','Luis Barrios','Luis Ortega','Randy Consuegra'],
        "Catchers":['Álvaro Noriega [es]','Christian Correa','Jair Camargo [es]'],'Infielders':['Derwin Pomare [es]','Héctor Acuña','Milton Ramos','Reynaldo Rodriguez','Samir Caraballo','Sneider Batista'],
        'Outfielders':[
'Efrain Contreras',
'Jonathan Lozada',
'Steve Brown']}
    liste_joueurs_football_colombie={"gb":["1 david ospina", 
        "22 eder chaux",
        "12 aldair quintana"],
        "df":["2 jhon lucumi",
        "13 yerry Mina",
        "4 santiago arias",
        "6 william tesillo",
        "2 stefan medina",
        "17 frank fabra ",
        "23 davinson sanchez",
        "3 jeison murillo"],
        "ml":["18 stiven mendoza",
        "5 mateus uribe",
        "10 james rodriguez",
        "11 juan guillermo cuadrado",
        "8 yairo moreno",
        "14 luis diaz",
        "16 jefferson lerma"],
        "at":["10 steven alzate",
        "20 roger martinez",
        "9 alfredo morelos",
        "21 luis muriel"]}
    liste_joueurs_basketball_USA={"1/2":["4	Derrick White"],	
"2/1":['5	Donovan Mitchell'],	
"2/3":['6	Joe Harris',
'9	Jaylen Brown'],	
"2":['7	Marcus Smart'],	
"3/4":['8	Harrison Barnes'],	
"3":['10	Jayson Tatum',
'14	Khris Middleton'],	
"4/5":['11	Mason Plumlee'],	
"5":['12	Myles Turner',	
'13	Brook Lopez'],
"1":["15	Kemba Walker"]}

    liste_joueurs_baseball_USA={"Pitchers":[
' 3 Clayton Andrews',
'32 Brandon Dickson',
'29 Parker Dunshee',
'27 J. P. Feyereisen',
'43 Brian Flynn',
'31 Tanner Houck',
'-- Spencer Howard',
'29 Tyler Johnson',
'36 Wyatt Mills',
' 8 Penn Murfee',
'44 Cody Ponce',
'50 Brooks Pounders',
'38 Clayton Richard',
'-- Connor Seabold',
'37 Noah Song',
'16 Caleb Thielbar',
"33 Daniel Tillo"],'Catchers':[
'17 Taylor Gushue',
'14 Erik Kratz',
'10 Daulton Varsho'],'Infielders':[
'23 Alec Bohm',
' 2 C. J. Chatham',
' 1 Jake Cronenworth',
'15 Bobby Dalbec',
' 5 Xavier Edwards',
'12 Andrew Vaughn'],'Outfielders':[
'22 Jo Adell',
' 4 Mark Payton',
'35 Brent Rooker',
'11 Drew Waters'] }
    liste_joueurs_football_japon={"gb":
['Masaaki Higashiguchi',	
'Eiji Kawashima',
'Daniel Schmidt'],
"df":['Wataru Endo',
'Tomoaki Makino',	
'Yasuyuki Konno',
'Yuto Nagatomo',	
'Gotoku Sakai',	
'Genta Miura',	
'Hiroki Sakai',	
'Gen Shoji',	
'Maya Yoshida'],	
"ml":['Yosuke Ideguchi',	
'Shinji Kagawa',	
'Takashi Inui',	
'Takefusa Kubo', 
'Makoto Hasebe',	
'Hotaru Yamaguchi'],	
"at":['Genki Haraguchi',	
'Takuma Asano',	
'Keisuke Honda',	
'Yuya Kubo',	
'Shinji Okazaki',	
'Yuya Osako'
]}
    liste_joueurs_football_france={
"g":["16 Steve Mandada",
"1	Alphonse Areola",	
"23	Mike Maignan"],	
"d":["2	Benjamin Pavard",	
"21	Léo Dubois",	
"4	Raphaël Varane", 
"3	Presnel Kimpembe",	
"5	Clément Lenglet",	
"15	Kurt Zouma",	
"19	Lucas Digne",	
"22	Benjamin Mendy"],	
"m":["17	Moussa Sissoko",	
"13	N'Golo Kanté",	
"12	Corentin Tolisso",	
"6	Tanguy Ndombele",	
"14	Mattéo Guendouzi"],	
"at":["8	Thomas Lemar",	
"9	Olivier Giroud",	
"7	Antoine Griezmann",	
"10	Kylian Mbappé",	
"18	Nabil Fekir",	
"20	Wissam Ben Yedder"
]}
    liste_joueurs_handball_france={
"gb":["12	Vincent Gérard",	
"24	Wesley Pardin"],	
"ALG":[
"15	Mathieu Grébille",	
"21	Michaël Guigou"],
"ALD":[	
"19	Luc Abalo",	
"28	Valentin Porte"],
"ARD":[	
"5	Nedim Remili",	
"10	Dika Mem"],
"DEF":[	
"27	Adrien Dipanda"],
"ARG":[	
"7	Romain Lagarde",	
"8	Elohim Prandi"],
"DC":[	
"9	Melvyn Richardson",	
"13	Nikola Karabatic"],	
"P":[
"20	Cédric Sorhaindo", 	
"23	Ludovic Fabregas",	
"30	Nicolas Tournat"	
]}
    liste_joueurs_football_australie={
"G":[
"1	Mathew Ryan",	
"12	Adam Federici",	
"18	Andrew Redmayne"],
"D":[	
"2	Miloš Degenek",	
"3	Brad Smith",	
"4	Rhyan Grant",
"8	Bailey Wright",	
"16	Aziz Behich",
"17	Josh Risdon",
"19	Harry Souttar",	
"20	Trent Sainsbury"],
"M":[	
"5	Kenneth Dougall",	
"6	James Jeggo",
"11	Ajdin Hrustic",	
"13	Aaron Mooy",
"22	Jackson Irvine",	
"23	Tom Rogić"],
"A":[
"7	Craig Goodwin",	
"9	Martin Boyle",
"10	Adam Taggart",	
"14	Brandon Borrello",	
"15	Mitchell Duke",
"21	Awer Mabil"
]}
    liste_joueurs_football_algerie={
"G":[
"1	Azzedine Doukha",	
"16	Alexandre Oukidja",	
"23	Raïs M'Bolhi"],	
"D":[
"2	Aïssa Mandi",	
"3	Mehdi Tahrat",	
"4	Djamel Benlamri",	
"5	Ayoub Abdellaoui",	
"6	Maxime Spano-Rahou",	
"12	Réda Halaïmia",
"20	Youcef Atal",
"21	Ramy Bensebaini"],	
"M":[
"7	Riyad Mahrez", 
"8	Youcef Belaïli",	
"10	Sofiane Feghouli",	
"14	Haris Belkebla",
"17	Adlène Guedioura",	
"18	Adem Zorgane",
"19	Mehdi Abeid",
"22	Ismaël Bennacer"],	
"A":[
"9	Baghdad Bounedjah",	
"11	Andy Delort",
"13	Islam Slimani",	
"15	El Arabi Hilal Soudani"
]}
    #USA,Colombie,France,Japon
    competition_football_20ans=[
    "Tahiti U-20 0 - 3 Senegal U-20",
"Mexique U-20 1 - 2 Italie U-20",
"Poland U-20 0 - 2 Colombie U-20",
"Japan U-20 1 - 1 Equateur U-20",
"24/05/2019",
"Honduras U-20 0 - 5 Nouvelle Zélande U-20",
"Qatar U-20 0 - 4 Nigeria U-20",
"Uruguay U-20 3 - 1 Norway U-20",
"Ukraine U-20 2 - 1 Etats-Unis U-20",
"25/05/2019",
"Portugal U-20 1 - 0 Corée du Sud U-20",
"France U-20 2 - 0 Arabie saoudite U-20",
"Panama U-20 1 - 1 Mali U-20",
"Argentine U-20 5 - 2 South Africa U-20",
"26/05/2019",
"Mexique U-20 0 - 3 Japan U-20",
"Senegal U-20 2 - 0 Colombie U-20",
"Equateur U-20 0 - 1 Italie U-20",
"Poland U-20 5 - 0 Tahiti U-20",
"27/05/2019",
"Honduras U-20 0 - 2 Uruguay U-20",
"Qatar U-20 0 - 1 Ukraine U-20",
"Norway U-20 0 - 2 Nouvelle Zélande U-20",
"Etats-Unis U-20 2 - 0 Nigeria U-20",
"28/05/2019",
"Panama U-20 0 - 2 France U-20",
"Portugal U-20 0 - 2 Argentine U-20",
"Arabie saoudite U-20 3 - 4 Mali U-20",
"South Africa U-20 0 - 1 Corée du Sud U-20",
"29/05/2019",
"Italie U-20 0 - 0 Japan U-20",
"Equateur U-20 1 - 0 Mexique U-20",
"Colombie U-20 6 - 0 Tahiti U-20",
"Senegal U-20 0 - 0 Poland U-20",
"30/05/2019",
"Nouvelle Zélande U-20 0 - 2 Uruguay U-20",
"Norway U-20 12 - 0 Honduras U-20",
"Nigeria U-20 1 - 1 Ukraine U-20",
"Etats-Unis U-20 1 - 0 Qatar U-20",
"31/05/2019",
"Mali U-20 2 - 3 France U-20",
"Arabie saoudite U-20 1 - 2 Panama U-20",
"Corée du Sud U-20 2 - 1 Argentine U-20",
"South Africa U-20 1 - 1 Portugal U-20"]
 #colombie,france,Japon
    competition_football_mondial_2018=[
   
    "Drapeau : Uruguay Uruguay	2",
 
 	"Drapeau : Portugal Portugal	1",	 
 	"Drapeau : Uruguay Uruguay	0",
 	"30 juin à Kazan",
 	" 	Drapeau : France France	2",	 
 	"Drapeau : France France	4",
 	"6 juillet à Kazan",
 	"Drapeau : Argentine Argentine	3",	 
 	"Drapeau : France France	1",
 	"2 juillet à Samara",
 	" 	Drapeau : Belgique Belgique	0",	 
 	"Drapeau : Brésil Brésil	2",
 	"11 juillet à Moscou (Stade Loujniki)",
 	"Drapeau : Mexique Mexique	0",
 	"Drapeau : Brésil Brésil	1",
 	"2 juillet à Rostov-sur-le-Don",
 	" 	Drapeau : Belgique Belgique	2",	 
 	"Drapeau : Belgique Belgique	3",
 	"7 juillet à Sotchi",
 	"Drapeau : Japon Japon	2",	 
 	"Drapeau : France France	4",
 	"1er juillet à Moscou (Stade Loujniki)",
 	" 	Drapeau : Croatie Croatie	2",
 	"Drapeau : Espagne Espagne	1ap (3)",
 	
 	"Drapeau : Russie Russie	1 tab(4)",	 
 	"Drapeau : Russie Russie	2ap (3)",
 	"1er juillet à Nijni Novgorod",
 	" 	Drapeau : Croatie Croatie	2 tab(4)",	 
 	"Drapeau : Croatie Croatie	1ap (3)",
 	"7 juillet à Samara",
 	"Drapeau : Danemark Danemark	1 tab(2)",	 
 	"Drapeau : Croatie Croatie	2 ap",
 	"3 juillet à Saint-Pétersbourg",
 	" 	Drapeau : Angleterre Angleterre	1",	 
 	"Drapeau : Suède Suède	1",
 	
 	"Drapeau : Suisse Suisse	0	 	Match pour la 3e place",
 	"Drapeau : Suède Suède	0",
 	"3 juillet à Moscou (Stade du Spartak)	14 juillet à Saint-Pétersbourg",
 	" 	Drapeau : Angleterre Angleterre	2",
 	"Drapeau : Colombie Colombie	1ap (3)	Drapeau : Belgique Belgique	2",
 	 
 	"Drapeau : Angleterre Angleterre	1 tab(4)	 	Drapeau : Angleterre Angleterre	0"]

    return {'Colombie':{'baseball':liste_joueurs_baseball_colombie,'football':liste_joueurs_football_colombie},
    'USA':{'baseball':liste_joueurs_baseball_USA,'basketball':liste_joueurs_basketball_USA},
    'Japon':{'football':liste_joueurs_football_japon},
    'France':{'football':liste_joueurs_football_france,'handball':liste_joueurs_handball_france},
    'Australie':{'football':liste_joueurs_football_australie},
    'Algérie':{'football':liste_joueurs_football_algerie}}